// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	withinterfaces "github.com/PFadel/go-presentations/gopherconbr2022/withinterfaces"
	mock "github.com/stretchr/testify/mock"
)

// Deliverable is an autogenerated mock type for the Deliverable type
type Deliverable struct {
	mock.Mock
}

// WithinDeliveryDistance provides a mock function with given fields: lat1, lng1, lat2, lng2, c
func (_m *Deliverable) WithinDeliveryDistance(lat1 float64, lng1 float64, lat2 float64, lng2 float64, c withinterfaces.Calculator) bool {
	ret := _m.Called(lat1, lng1, lat2, lng2, c)

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, float64, float64, float64, withinterfaces.Calculator) bool); ok {
		r0 = rf(lat1, lng1, lat2, lng2, c)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewDeliverable interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeliverable creates a new instance of Deliverable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeliverable(t mockConstructorTestingTNewDeliverable) *Deliverable {
	mock := &Deliverable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
